project:
  type: website

website:
  title: "Ecosystem Monitoring for Management Application (EMMA)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model_summary.qmd
        text: Model Summary

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

