---
title: "parks"
---

Park Information

```{r prep_parks,echo=FALSE,warning=FALSE,message=FALSE}
library(targets)
library(tidyverse)
library(leaflet)
library(sf)
library(gt)

tar_load(parks) 
# need to merge each complex into a single geometry


  cn <- parks$cape_nature%>%
      group_by(COMPLEX)%>%
      summarise() %>%
  rename(Park = COMPLEX)

  np <- parks$national_parks%>%
    group_by(CUR_NME)%>%
    summarise() %>%
    rename(Park = CUR_NME)
  
  
  parks_sf <- bind_rows(cn,np)
  
  rm(np,cn)
  
  
  base_url <- "https://adamwilsonlab.github.io/emma_report/reports/"
  
    reports <- 
  data.frame(report = list.files("reports/")) %>%
    mutate(url = paste(base_url,report,sep = ""),
           park_name = gsub(pattern = "report.",replacement = "",x = report),
           park_name = gsub(pattern = ".html",replacement = "",x = park_name),
           park_name = gsub(pattern = "_",replacement = " ",x = park_name)) %>%
      mutate(
          park = glue::glue("[{park_name}]({url})"),
          park = map(park, gt::md))
  
  parks_sf <-
  parks_sf %>%
    inner_join(y = reports,
               by = c("Park"="park_name"))%>% 
    st_transform(crs = st_crs(4326))%>% 
   mutate(tag = paste0("Park: <a href=", url,">",Park , "</a>"))

  bbox <- st_bbox(parks_sf) %>%
  as.vector()
```

```{r park_map, fig.width = 10, fig.height = 7, echo = FALSE, warning = FALSE, message = FALSE}


  leaflet(data = parks_sf) %>%
  addProviderTiles("Esri.NatGeoWorldMap", group = "NatGeo") %>%
    #addProviderTiles("NASAGIBS.ModisTerraTrueColorCR", group = "True Colors") %>%
    addProviderTiles(providers$Esri.WorldImagery, group = "World Imagery") %>%
  addPolygons(color = "black",
              stroke = TRUE,
              fill = TRUE,
              group = "Park",
              popup = ~tag) %>%
  addLayersControl(
    baseGroups = c("NatGeo","World Imagery"),
    options = layersControlOptions(collapsed = FALSE),position = "topright") %>%
  fitBounds(bbox[1], bbox[2], bbox[3], bbox[4])






    reports%>%
    dplyr::select(park)%>%
    rename(Park = park)%>%
    gt()%>%
  cols_align(align = "left")
```
